[env:bluepill]
platform        = ststm32
board           = bluepill_f103c8
framework       = arduino
monitor_speed   = 115200
upload_protocol = stlink

; WiFi handled by ESP8266 AT coprocessor (ESP-AT v2.4+)
; Wiring: STM32 PA2(TX) → ESP RX  |  PA3(RX) → ESP TX  |  CH_EN → 3.3V

[env:nucleo_f446re]
platform        = ststm32
board           = nucleo_f446re
framework       = arduino
monitor_speed   = 115200
upload_protocol = stlink
